# Generated by Django 2.2 on 2019-05-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='products',
            field=models.ManyToManyField(related_name='attributes', to='ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_region_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ShippingRegion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='ecommerce.Category'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='ecommerce.ShippingRegion'),
        ),
    ]
