# Generated by Django 2.2 on 2019-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20190501_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
