# Generated by Django 2.2 on 2019-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20190502_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(related_name='shopping_carts', to='ecommerce.Product'),
        ),
    ]
