# Generated by Django 2.2 on 2019-05-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20190502_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='date_modified',
        ),
    ]
