# Generated by Django 2.2 on 2019-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20190504_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='buy_now',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='buy_now',
            field=models.BooleanField(default=True),
        ),
    ]
