# Generated by Django 2.2 on 2019-05-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20190504_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='products',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='products',
            field=models.ManyToManyField(related_name='attributes', to='ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
