# Generated by Django 2.2 on 2019-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20190510_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='attributes',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='attributes',
            field=models.ManyToManyField(related_name='shopping_cart_items', to='ecommerce.AttributeValue'),
        ),
    ]
