# Generated by Django 2.2 on 2019-05-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20190510_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='attributes',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='attributes',
            field=models.ManyToManyField(related_name='order_detail', to='ecommerce.AttributeValue'),
        ),
    ]
